исправляет стилизацию
htmlacademy-htmlcss/1359017-sedona-33 pull request #5
Opened 2022-02-14 11:24 UTC by ekaterina-bkv

2022-02-14 13:21 UTC, ekaterina-bkv commented
исправляет стилизацию

2022-02-14 14:55 UTC, mkolotovich requested changes

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    font-family: "PT Sans"; sans-serif;
здесь точку с запятой не надо между значениями. Просто запятую иначе он воспринимает как неверное значение

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селектор .navigation-user .navigation-item:last-child .navigation и задайте ему font-size: 16px; line-height: 20px; color: #FFFFFF; text-transform: uppercase; background: #756257;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    font-style: bold;
У этого свойства нет такого значения. Тут может быть значение normal по макету. А значение bold задается свойству font-weight

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-align: Center
задайте text-transform: uppercase;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    font-family: "PT Sans"
точку с запятой пропустили в конце свойства

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    text-align: center;
Задайте color: #333333;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +}
Создайте селектор h3.advantage-title и задайте ему font-size: 24px; line-height: 28px; text-transform: uppercase;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    font: "PT Sans";
Здесь вы скорее всего хотели использовать свойство font-family

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    line-height: 21 px;
Между значением и единицей измерения нельзя использовать пробел. Это не корректное значение

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +}
Создайте селектор h4.advantage-title и задайте ему font-size: 24px; line-height: 28px; text-transform: uppercase;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +}
Создайте селектор .advantage-item:nth-child(n+2):nth-child(-n+4) .advantage-diskription и задайте ему color: #333333;

2022-02-14 14:55 UTC, mkolotovich commented on styles/styles.css
> +    size: 18px;
тут вы скорее всего имели ввиду свойство font-size

2022-02-15 13:20 UTC, mkolotovich requested changes
исправьте не схлопнутые замечания с прошлой проверки плсю добавились новые. Элементу `<div class="diskription-4">` добавьте класс diskription-2. Селектору .button-usual задайте     background: transparent;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
> +src: url("fonts/ptsans-400.woff2") format("woff2");
путь к файлу шрифтов должен начинаться с ../ чтобы нам подняться на уровень вверх

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
> +src: url("fonts/ptsans-700.woff2") format("woff2");
путь к файлу шрифтов должен начинаться с ../ чтобы нам подняться на уровень вверх из папки стилей

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>      font: "PT Sans";
Здесь необходимо использовать свойство font-family

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>      background-color:#83B3D3;
Задайте text-transform: uppercase;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .appointment-form input и задайте ему font-family: PT Sans; font-size: 18px;
line-height: 26px; background: #F2F2F2;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
Создайте селектор .appointment-form input::placeholder и задайте ему color: #000000;
opacity: 0.6;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селектор .filter input и задайте ему font-family: PT Sans; font-size: 18px;
line-height: 23px;     background: transparent;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селектор .filter input::placeholder и задайте ему color: #FFFFFF;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>      line-height: 21px;
задайте text-transform: uppercase;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>      line-height: 39px;
задайте text-transform: uppercase;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селектор .select-control и задайте ему font-family: PT Sans; font-size: 18px;
line-height: 23px; color: #333333;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селектор .product-card-link и задайте ему text-decoration: none;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  .product-card-price{
задайте color: #333333;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селекторк .main-inner .title и задайте ему color: #000000;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>  }
Создайте селекторк .main-inner .no-spam и задайте ему color: #333333;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
>      line-height: 28 px;
между значением и единицей измерения нельзя ставить пробел

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
> +    background-image: url("../images/catalog-background-1.jpg");
задайте     background-repeat: no-repeat;

2022-02-15 13:20 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте background: #F2F2F2;

2022-02-16 12:46 UTC, mkolotovich requested changes

2022-02-16 12:46 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .main-inner .mailing и задайте ему     background-image: none;

2022-02-16 14:32 UTC, merged